### 🔧 LOGIN REQUEST (FINAL)
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "shakir@gmail.com",
  "password": "1234567"
}

###

###🔧 GET USER PROFILE (FINAL)
POST  http://localhost:5000/get_user_and_profile
Content-Type: application/json

{
  "token": "47d3e21c870751e57438a0fbe66301d627b3c27cc4120f1ec08eea3d596a82a2"
}

###

###🔧 UPDATE PROFILE DATA
POST http://localhost:5000/update_profile_data
Content-Type: application/json

{
  "token": "47d3e21c870751e57438a0fbe66301d627b3c27cc4120f1ec08eea3d596a82a2",
  "bio": "I'm a Software Engineer at Amazon"
}

###

###GET ALL USERS
GET  http://localhost:5000/get_all_users
Content-Type: application/json

{
  "profiles": [
    {
      "_id": "...",
      "bio": "...",
      "userId": {
        "email": "shakir@gmail.com",
        "userName": "shakir",
        "profilePicture": "image.png"
      }
    }
  ]
}




