###user 
POST http://localhost:5000/api/register
Content-Type: application/json

{
  "name": "Ash",
  "email": "ash@gmail.com",
  "password": "123456",
  "userName": "ashh0x"
}

### REGISTER
POST http://localhost:5000/api/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@gmail.com",
  "password": "123456",
  "userName": "testuser"
}

###
POST http://localhost:5000/api/register
Content-Type: application/json

{
  "name": "jex",
  "email": "jex@gmail.com",
  "password": "123456",
  "userName": "jex"
}

### Login 
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email": "ash@gmail.com",
  "password": "123456"
}

### geting profile
POST http://localhost:5000/api/get_user_and_profile
Content-Type: application/json

{
  "token": "d2277c444277e3b17979ff08c716a9aac867baf941f88e73845bb08f797bff8c"
}


###UPDATE USER PROFILE
POST http://localhost:5000/api/user_update
Content-Type: application/json

{
  "token": "d2277c444277e3b17979ff08c716a9aac867baf941f88e73845bb08f797bff8c",
  "userName": "az",
  "email": "az@gmail.com"
}

